# Generated by Django 5.1.6 on 2025-03-19 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_alter_district_name_alter_specialty_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hospital',
            name='district',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='map.district'),
        ),
    ]
